version: '3.8'

volumes:
  pg_data:

services:
  postgres:
    image: postgres:12.2-alpine
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: covid19
      POSTGRES_HOST_AUTH_METHOD: trust

  rabbit:
    image: rabbitmq:3.8.3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
